import { useState, useEffect, useRef } from 'react'
import { motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import './MarketUCaseStudy.css'

gsap.registerPlugin(ScrollTrigger)

// ─── Data Extraction from growos_case_study.json ──────────────────────────────

const META = {
  type: "B2B SaaS — Autonomous Marketing OS for EdTech and Coaching Institutes",
  role: "Sole Product Architect & Lead UX Designer",
  builtAt: "NorthStar Academy — AICPA Gold Partner CPA Coaching Institute",
  timeline: "Discovery: 4w → Prototype: 6w → Build: 12w",
  status: "Modules 1 + 2 live in production. Modules 3–5 in design and build.",
  competitivePositioning: "Semrush + Hootsuite + Google Search Console + Vercel + Slack + Zoom — replaced by one platform that executes autonomously instead of just reporting",
  targetSegments: [
    "EdTech coaching institutes (CPA, CMA, ACCA, MBA prep, UPSC) — primary segment",
    "Digital-first professional services firms (CA firms, legal, finance advisory)",
    "Series A/B startups with lean marketing teams in India"
  ],
  techStack: [
    "GitHub API (live deploy)", "DigitalOcean App Platform", "Vercel SDK (landing pages)",
    "Google Search Console API", "Claude / OpenAI APIs", "Pinecone (RAG Vector Base)",
    "Razorpay (influencer payouts)", "AiSensy WABA (WhatsApp tracking)"
  ]
}

const OUTCOMES = [
  { id: 'mu-cnt-velocity', to: 18, suffix: '', label: 'Blog posts/month (from 2/mo via agency)' },
  { id: 'mu-cnt-pages', to: 23, suffix: '', label: 'City landing pages deployed in 4 days' },
  { id: 'mu-cnt-rankings', to: 6, suffix: ' days', label: 'First GSC-tracked keyword rankings' },
  { id: 'mu-cnt-savings', to: 55, suffix: 'k', label: '₹55,000/mo agency retainer eliminated' },
  { id: 'mu-cnt-consol', to: 7, suffix: '→1', label: 'Tools consolidated into single OS' }
]

const RESEARCH_METHODS = [
  {
    num: '01',
    method: 'Embedded Operational Audit',
    metric: '22',
    metricLabel: 'participants',
    duration: '4 weeks inside marketing team',
    details: ' shadow audit across 6 squads — content, video, SEO, paid ads, social, outreach. Tracked everyday bottlenecks.',
    bullets: [
      'Chrome tab audit: marketing members run 11.4 tabs open simultaneously',
      'Topic ideation to publish cycle time averaged 18 days for a blog post',
      'Average of 47 WhatsApp messages sent internally to coordinate one post',
      'Attribution gap: zero attribution tracking for 92% of incoming WhatsApp leads'
    ]
  },
  {
    num: '02',
    method: 'In-Depth Interviews',
    metric: '31',
    metricLabel: 'interviewees',
    duration: '60-min qualitative interviews',
    details: 'Interviews with marketing managers, founders, and content creators in Indian coaching spaces.',
    bullets: [
      '6 Marketing Heads, 8 Content Managers, 5 SEOs, 5 Social Media Managers',
      'Focal question: "Walk me through the last piece of content you published — from brief to result."',
      '87% of heads said they cannot trace admissions to specific content pieces',
      '77% noted getting content live on WordPress takes too long due to developer queues'
    ]
  },
  {
    num: '03',
    method: 'Tool Usage Survey',
    metric: '89',
    metricLabel: 'respondents',
    duration: 'Quantitative survey',
    details: 'Profiles of marketing managers and content leads at Indian EdTech firms with 20-100 employees.',
    bullets: [
      'Average of 7.4 separate tools in active use by marketing teams',
      'Average monthly spend of ₹28,500 on marketing tools (excl. agency)',
      '84% use WhatsApp as primary channel for content review and approval',
      'Only 23% of managers look at GA4 more than once per week due to complexity'
    ]
  },
  {
    num: '04',
    method: 'Competitive Teardown',
    metric: '16',
    metricLabel: 'tools evaluated',
    duration: 'Deep features mapping',
    details: 'Audited Semrush, Ahrefs, SurferSEO, Buffer, HubSpot, Sprout Social, Notion, AiSensy, etc.',
    bullets: [
      'The Execution Gap: Tools suggest keywords but cannot push them live to the site',
      'The Attribution Gap: No tool connects content creation to WhatsApp leads and CRM conversions',
      'The Collaboration Gap: Content calendars assume isolation, pushing reviews to WhatsApp group chats'
    ]
  }
]

const AFFINITY_THEMES = [
  {
    theme: "The Execution Gap",
    desc: "Every insight generated by a marketing tool requires a human to act on it. Semrush says 'this keyword is an opportunity' — someone still has to write, review, upload, add schema, and push it live. GrowOS closes this: keyword identified → content generated → deployed to live site autonomously.",
    stat: "Average time from keyword research to published post: 18 days. GrowOS target: <4 hours."
  },
  {
    theme: "The Attribution Black Hole",
    desc: "91% of EdTech marketing leads cannot be traced to specific content. GA4 tracks sessions, CRM tracks leads, WhatsApp tracks the inquiry. Disconnected systems mean marketing spends ₹2-5L/month without knowing what converted.",
    stat: "Only 8% of leads were attributable to content before GrowOS."
  },
  {
    theme: "The WhatsApp Approval Tax",
    desc: "84% of EdTech teams use WhatsApp for content review. Content gets lost in threads, feedback is informal and inconsistent, and editors send ~47 WhatsApp messages per piece before it goes live.",
    stat: "Content approval cycles took 4.3 days on average."
  },
  {
    theme: "The Semrush Paradox",
    desc: "Semrush is the most purchased SEO tool but the most under-used. Teams buy it for ₹8k-38k/month, use 6% of features, and generate reports that no one acts on because execution is disconnected.",
    stat: "Average time from Semrush report to website implementation: 11 days."
  }
]

const JTBDS = [
  {
    id: "JTBD-01",
    actor: "Head of Marketing",
    job: "When my CEO asks me what's working, I want to show a direct line from a specific content piece to a lead to an enrollment — so I can defend my budget and double down on what converts.",
    workaround: "Compile screenshots from GA4, WhatsApp chat logs, and CRM reports in a slide deck."
  },
  {
    id: "JTBD-02",
    actor: "Content Manager",
    job: "When I identify a keyword opportunity, I want to go from 'keyword found' to 'content live on website' in under 24 hours — so we can capture ranking windows before competitors.",
    workaround: "Google Doc outlines sent to freelancers, revised over WhatsApp, queued for developers."
  },
  {
    id: "JTBD-04",
    actor: "PR & Partnerships Manager",
    job: "When I run an influencer campaign, I want to manage briefs, contract agreements, content approval, and payments from one dashboard — so I'm not chasing 12 influencers over WhatsApp.",
    workaround: "Individual WhatsApp chats, Word doc briefs, PDF contracts, bank transfers tracked in Excel."
  },
  {
    id: "JTBD-06",
    actor: "SEO Manager",
    job: "When I want to improve local SEO, I want to generate schema, add it to the page, and deploy live — without waiting for the developer queue that adds weeks to every minor technical SEO change.",
    workaround: "Write schema JSON, email developer, wait in Jira backlog, inspect source code later."
  }
]

const KEY_INSIGHTS = [
  {
    num: "INS-01",
    title: "The problem is the distance between insight and execution",
    evidence: "Every tool researches or reports. Not a single tool pushes output to a live website. The gap requires a human, developer, or agency every time.",
    principle: "Close loops with autonomous execution. When keyword is identified, generate, optimize, and deploy in the same platform session."
  },
  {
    num: "INS-02",
    title: "WhatsApp is the primary workflow tool — and it is chaotic",
    evidence: "84% of teams approve content in WhatsApp. It lacks version control, formal state tracking (approved/rejected), and audit trails.",
    principle: "Make in-platform review and approval faster and easier than sending a WhatsApp link."
  },
  {
    num: "INS-03",
    title: "Attribution is the core value proposition, not a feature",
    evidence: "91% cannot trace a lead to a specific blog. When shown content-to-enrollment pipeline tracing, 26 of 31 managers said it would justify the stack budget.",
    principle: "Every content asset gets a tracking ID at creation. Attribution maps from content → session → WhatsApp click → lead → conversion."
  },
  {
    num: "INS-04",
    title: "The GitHub-to-website pipeline is the ultimate product moat",
    evidence: "No marketing tool writes to the codebase. Connecting code deploy makes GrowOS an execution system, bypassing developer queues entirely.",
    principle: "The deploy button is first-class. Allow non-technical managers to safely commit content to a branch and monitor deployment status."
  }
]

const PERSONAS = [
  {
    id: "P-01",
    name: "Kiran Reddy",
    archetype: "The Attribution-Hungry Growth Head",
    age: 35,
    role: "Head of Marketing / Growth",
    company: "CPA/CMA coaching institute, 80 employees",
    location: "Hyderabad, India",
    tools: ["Semrush", "SEO Agency", "Buffer", "GA4", "Notion", "WhatsApp"],
    quote: "I spend ₹78,000/month on marketing tools and when my Director asks which blog generated enrollments, I cannot answer. I know keywords are ranking, but not if they generate revenue.",
    goals: [
      "Prove marketing ROI in rupee revenue, not sessions or impressions",
      "Reduce dependency on slow external SEO agencies",
      "Get content live faster to seize competitive keywords"
    ],
    frustrations: [
      "Semrush provides keyword insights but agency takes weeks to write and publish",
      "Content reviews are scattered across Google Docs and WhatsApp groups",
      "No single database ties blog readers to WhatsApp inquiries and enrollments"
    ],
    success: "Open GrowOS on Monday morning, see that the blog on 'CPA exam fees India' drove 34 WhatsApp leads and 3 enrollments, and show that to the Director in 10 seconds.",
    state: "Capable and results-driven, but flying blind on attribution.",
    avatar: "KR"
  },
  {
    id: "P-02",
    name: "Divya Sharma",
    archetype: "The Speed-Blocked Content Manager",
    age: 27,
    role: "SEO & Content Manager",
    company: "Same institute as Kiran, 80 employees",
    location: "Bangalore, India",
    tools: ["Google Docs", "Semrush", "WordPress", "WhatsApp", "Canva", "Buffer"],
    quote: "I write the content, send for review on WhatsApp, wait 4 days, make edits, and then wait for a developer to upload it. The keyword ranking window passes before we are live.",
    goals: [
      "Go from keyword idea to live published blog in under 4 hours",
      "Publish schema and landing pages without developer assistance",
      "Automate social post captions directly from blog assets"
    ],
    frustrations: [
      "No backend access to WordPress — blocked by development queues",
      "WhatsApp approvals are chaotic, lacking clear feedback histories",
      "Technical SEO schema (JSON-LD) requires developers to manually paste into headers"
    ],
    success: "Keyword selected in GrowOS, outline generated, draft edited in the editor, and deployed live with structured schema and UTM tags in the same afternoon.",
    state: "Highly skilled, but bottlenecked by developer dependencies.",
    avatar: "DS"
  },
  {
    id: "P-03",
    name: "Arjun Mehta",
    archetype: "The Chaos-Coordinating Influencer Manager",
    age: 31,
    role: "PR & Partnerships Manager",
    company: "Mid-size EdTech, 3 running campaigns",
    location: "Mumbai, India",
    tools: ["WhatsApp", "Gmail", "Excel Sheets", "Google Drive", "Bank Transfers"],
    quote: "I'm managing 12 influencers across 3 campaigns. 12 chats, 12 payment lists, and 6 video drafts waiting for review. I have no dashboard to track campaign UTM performance.",
    goals: [
      "Centralize influencer briefs, contract e-signing, and content approval",
      "Track influencer UTMs automatically to see who converts",
      "Automate Razorpay payouts to influencers once content is approved"
    ],
    frustrations: [
      "Influencer drafts are sent as raw files in WhatsApp threads, easily lost",
      "Excel tracking sheets are prone to calculation errors and payment delays",
      "No line connecting influencer posts to actual CRM lead conversions"
    ],
    success: "Open COLLABORATE, see the status of all 12 deals (briefed, signed, uploaded, approved, paid), and trace UTM performance in one UI.",
    state: "Organized by nature, but fighting tool chaos.",
    avatar: "AM"
  },
  {
    id: "P-04",
    name: "Rajesh Kumar",
    archetype: "The Founder Who Wants One Answer",
    age: 44,
    role: "Founder & Managing Director",
    company: "NorthStar Academy, ₹8 Cr ARR",
    location: "Hyderabad, India",
    tools: ["Email", "CRM Reports", "WhatsApp Summaries"],
    quote: "I spend ₹12 lakhs/month on marketing. The team gives me reports with 200 metrics. I want to know one thing: for every rupee I spend, how many rupees of admission revenue do I get back?",
    goals: [
      "Simple metric: marketing spend → lead → admission → revenue",
      "Cut down agency overhead and subscription tool stack costs",
      "Predict enrollment growth based on content velocity"
    ],
    frustrations: [
      "Marketing reports contain disconnected GA4, lead count, and sales sheets",
      "SEO agencies present backlink stats with zero transparency on revenue impact",
      "No clarity on what blogs or campaigns actually deserve credit for enrollments"
    ],
    success: "Open the Executive Dashboard on phone, see: ₹12L spent → 847 leads → 43 enrolled → ₹38L revenue. Plus a breakdown of best channels.",
    state: "Results-oriented, impatient with complexity. Will pay for clarity, not reports.",
    avatar: "RK"
  }
]

const HMW_QUESTIONS = [
  { hmw: "How might we eliminate the gap between 'keyword identified' and 'content live on website' — making it a same-day action, not an 18-day project?", target: "Targeting: Kiran & Divya" },
  { hmw: "How might we connect every piece of content to the leads and enrollments it generates — so decisions are made with attribution data?", target: "Targeting: Kiran & Rajesh" },
  { hmw: "How might we make content approval faster than a WhatsApp message — so teams stop routing drafts through chat groups?", target: "Targeting: Divya & Arjun" },
  { hmw: "How might we turn influencer management from 12 parallel WhatsApp chats into a single structured, auto-paid workflow?", target: "Targeting: Arjun" }
]

const DESIGN_PRINCIPLES = [
  { title: "Execute, don't just recommend", desc: "Every competitor tells you what is wrong. GrowOS implements the fix. Insights are connected to one-click deploys. The system is an execution engine, not a advice generator." },
  { title: "Attribution is the foundation", desc: "Attribution cannot be retrofitted. Every asset is tagged at birth. UTMs are auto-generated and passed from session to WhatsApp, CRM, and revenue conversion databases." },
  { title: "Deploy is table stakes, not advanced", desc: "GitHub-to-production deployment is the core moat. The experience must feel safe and natural. Non-technical content writers must feel confident hitting 'Deploy'." },
  { title: "Replace WhatsApp on speed", desc: "The goal of collaboration is to displace WhatsApp. Approvals must be faster and simpler. Review systems must load instantly on mobile for on-the-go managers." }
]

const IA_MODULES = [
  {
    id: "M-01",
    name: "CREATE",
    tagline: "Go from keyword to content outline & drafts in one session",
    status: "live",
    tools: [
      { name: "KW Planner", desc: "Keyword research powered by Claude. Evaluates search volume, keyword difficulty, intent, and content gaps based on actual GSC search data." },
      { name: "Blog Planner", desc: "EEAT outlines and full-draft editor. Generates headings, LSI keyword targets, and local GEO signals tailored to local student segments." },
      { name: "Social Planner", desc: "Generates social campaign text, reel scripts, LinkedIn posts, and WhatsApp broadcast templates from any published blog in one click." },
      { name: "Landing Pages", desc: "HTML landing pages with metadata and structured schemas. Deploys directly to Vercel subdomains with XOLOX lead capture forms." }
    ]
  },
  {
    id: "M-02",
    name: "DEPLOY",
    tagline: "Push content and SEO fixes live without a developer",
    status: "live",
    tools: [
      { name: "GitHub Connect", desc: "Reads site code, commits content updates, and submits Pull Requests to a /content branch for review." },
      { name: "DO / Vercel Deploy", desc: "Triggers DigitalOcean or Vercel build pipelines on branch update and monitors deployment status logs in real time." },
      { name: "Google Search Console", desc: "Auto-submits newly deployed URLs to GSC indexing queue and alerts team on search crawl issues." },
      { name: "Push Live Panel", desc: "Shows all pending file updates, staging previews, build statuses, and one-click rollback options." }
    ]
  },
  {
    id: "M-03",
    name: "DISTRIBUTE",
    tagline: "Schedule content and outreach target backlink builders",
    status: "partial",
    tools: [
      { name: "Social Scheduling", desc: "Schedules content queues for LinkedIn, Instagram, and YouTube. Automatically links campaign metrics to tracking hashes." },
      { name: "Backlink Manager", desc: "Identifies link acquisition targets, tracks outreach conversation statuses, and monitors follow/nofollow indexing." },
      { name: "Email Campaigns", desc: "Syncs with CRM lead lists to send targeted program newsletters with tracking parameters." }
    ]
  },
  {
    id: "M-04",
    name: "TRACK",
    tagline: "Connect tracking IDs to customer leads and conversions",
    status: "roadmap",
    tools: [
      { name: "Content Attribution", desc: "Maps revenue and leads back to source content. First-of-its-kind content revenue scoreboard." },
      { name: "UTM Manager", desc: "Centralizes UTM templates, removing manual tag construction errors from marketing operations." },
      { name: "Channel ROI Report", desc: "Aggregated dashboard presenting advertising and organic spend vs enrollment revenue for founders." }
    ]
  },
  {
    id: "M-05",
    name: "COLLABORATE",
    tagline: "Manage campaign approvals and influencer payments in-app",
    status: "roadmap",
    tools: [
      { name: "PR Workspace", desc: "Collaboration zone for content draft review. Replaces WhatsApp feedback loops with versioned comments." },
      { name: "Influencer Deals", desc: "Manages influencer briefs, contract signatures, file uploads, and Razorpay payout integrations." },
      { name: "Approval Workflows", desc: "Multi-stage review paths with configurable SLA deadlines and automatic notification reminders." }
    ]
  }
]

const UX_FLOWS = [
  {
    flow_id: "UXF-01",
    flow_name: "Keyword to Live Blog — Same Day",
    actor: "Divya Sharma (Content Manager)",
    trigger: "wants to rank for 'CPA exam fees in India'",
    goal: "Publish and index optimized blog page in one afternoon",
    steps: [
      { step: 1, screen: "KW Planner", action: "Divya enters 'CPA exam fees India' in the keyword input.", decision: "Surfaces keyword card: volume 2,400/mo, KD 34 (easy), competitor SERP map, and content gap notice." },
      { step: 2, screen: "Blog Planner Outline", action: "Clicks 'Create Blog'. Evaluates generated outline: H1 structure, 8 sections, PAA questions, and location entities.", decision: "Allows inline edits. Divya refines the heading structures before generation." },
      { step: 3, screen: "Blog Editor — Draft Mode", action: "Clicks 'Generate Draft'. Edits content, adds a faculty quote for EEAT verification, and verifies GSC preview.", decision: "UTM attributes are automatically injected into all internal course CTA links." },
      { step: 4, screen: "PR Workspace — Approval", action: "Clicks 'Send for Review'. Selects Kiran Reddy as editor.", decision: "Notification goes to Kiran on phone. Kiran opens, writes comments, and clicks 'Approve'." },
      { step: 5, screen: "Deploy Console", action: "Divya receives approved notice. Clicks 'Deploy to Website'.", decision: "GrowOS commits files to the GitHub repo, triggering DigitalOcean build logs (Queued → Building → Live)." },
      { step: 6, screen: "Google Search Console", action: "Deployment completes. GrowOS submits the live URL to GSC index API.", decision: "GSC response returns success. Status card updates: 'URL submitted — indexing pending'." }
    ],
    edge_cases: [
      "Deploy failure: If DO build fails, developer is notified with stack trace while content rollbacks automatically.",
      "Keyword collision: Alerts if team already has a draft or post targetting the same focus keyword."
    ],
    metrics: ["Time to publish (target < 4 hrs)", "Approval cycle time", "Staging preview views", "GSC submission rate"]
  },
  {
    flow_id: "UXF-02",
    flow_name: "Attribution — Content to Admissions",
    actor: "Kiran (Growth) + Rajesh (Founder)",
    trigger: "Director requests performance overview for the quarter",
    goal: "Verify exactly which blog post drove enrollment revenue in 2 minutes",
    steps: [
      { step: 1, screen: "Attribution Dashboard", action: "Kiran opens the dashboard. Table loads with content sorted by revenue.", decision: "Attribution columns: Sessions | Leads | CRM Synced | Enrolled | Attributed Revenue." },
      { step: 2, screen: "Asset Breakdown Modal", action: "Kiran highlights the 'CPA exam fees India' blog post entry.", decision: "Row expands to reveal: 47 WhatsApp inquiries, 3 CRM student records, and ₹2,34,000 in revenue." },
      { step: 3, screen: "Channel ROI Report", action: "Kiran opens the high-level Channel Report to aggregate channels.", decision: "Presents channel blocks: Blog (₹8.2L), WhatsApp (₹4.4L), Instagram (₹3.1L) with calculated ROAS." },
      { step: 4, screen: "Executive Summary Mobile", action: "Rajesh logs into GrowOS from his mobile phone.", decision: "Displays Founder layout: ₹11.2L total spend → 43 enrollments → ₹38L revenue (3.4x ROAS) with zero detailed tables." }
    ],
    edge_cases: [
      "Multi-touch path: Lead clicked a blog, then got a WhatsApp blast. Default attribution model is set to first-click content attribution.",
      "Anonymous click: If click lacks cookie history, lead defaults to channel direct search group."
    ],
    metrics: ["Attribution coverage rate (> 75%)", "Report generation time (target < 2 min)", "CRM lead match rate"]
  },
  {
    flow_id: "UXF-03",
    flow_name: "Influencer Campaign Management",
    actor: "Arjun Mehta (PR Manager)",
    trigger: "Launching awareness campaign with 5 micro-influencers",
    goal: "Manage briefs, contract signatures, review drafts, and trigger Razorpay payouts inside the dashboard",
    steps: [
      { step: 1, screen: "Campaign Manager", action: "Arjun creates 'CPA Awareness Q3'. Adds 5 influencer accounts.", decision: "Table initializes with columns: Signatus, Deliverable, Approval, Razorpay, Status." },
      { step: 2, screen: "Brief Builder", action: "Creates campaign brief outline. System auto-populates USPs from brand base.", decision: "Sends brief and auto-generated contract agreement to all 5 influencers." },
      { step: 3, screen: "Deals Tracker", action: "Influencers e-sign agreements. Status shifts to 'Awaiting Submission'.", decision: "Ensures legal and compliance checks are satisfied before submission features open." },
      { step: 4, screen: "Review Panel", action: "3 influencers upload draft video files. Arjun plays them in-app.", decision: "Comments directly on video timelines. Requests revision on 1 draft for missing the brand tag." },
      { step: 5, screen: "Payout Processor", action: "Arjun clicks 'Approve' on the 2 correct drafts.", decision: "Razorpay Payout API triggers, transferring payments. Influencer status changes to 'Paid'." }
    ],
    edge_cases: [
      "Contract rejection: If influencer requests term changes, contract unlocks for editor review.",
      "Payment failure: If Razorpay API rejects due to wallet balance, payout queues and manager gets alert."
    ],
    metrics: ["Influencer submission turnaround", "Approval cycle time (vs 4.3d WhatsApp)", "Razorpay success rate"]
  }
]

const INTEGRATIONS = [
  { name: "GitHub API", purpose: "Content file commits, pull request creation, technical SEO updates", auth: "OAuth App", criticality: "Core" },
  { name: "Vercel SDK", purpose: "On-demand city landing page deployment and domain routing", auth: "Vercel Token", criticality: "Core" },
  { name: "Claude API", purpose: "SEO keyword analysis, blog structures, content editing, and social copywriting", auth: "API Key", criticality: "Core" },
  { name: "GSC API", purpose: "Indexing requests, crawl monitoring, and performance data sync", auth: "Google OAuth", criticality: "Core" },
  { name: "XOLOX CRM", purpose: "Lead pipeline syncing, attribution tags, and conversion tracking", auth: "API Key", criticality: "Critical" },
  { name: "Razorpay Payout", purpose: "Automated contractor e-contracts and instant milestone payouts", auth: "Key + Secret", criticality: "High" },
  { name: "AiSensy / WABA", purpose: "WhatsApp template tracking, click redirects, and lead triggers", auth: "API Key", criticality: "High" }
]

const PRIORITIZATION = [
  { id: "F-01", name: "KW & Blog Planner outline engine", module: "CREATE", priority: "P0", status: "Built", metric: "Outline generation <30 min" },
  { id: "F-02", name: "GitHub/Vercel deploy connector", module: "DEPLOY", priority: "P0", status: "Built", metric: "Deploy to live site <5 min" },
  { id: "F-03", name: "Google Search Console submission", module: "DEPLOY", priority: "P0", status: "Built", metric: "GSC crawl trigger in 5 min" },
  { id: "F-04", name: "Local SEO landing pages generator", module: "CREATE", priority: "P0", status: "Built", metric: "Landing page setup <10 min" },
  { id: "F-05", name: "Content-to-Enrollment Tracker", module: "TRACK", priority: "P0", status: "In build", metric: "Attribution mapping >75% leads" },
  { id: "F-07", name: "Social campaign generator wizard", module: "CREATE", priority: "P1", status: "Built", metric: "Social posts scheduled per blog >4" },
  { id: "F-09", name: "PR Approval Workflows dashboard", module: "COLLABORATE", priority: "P1", status: "Designed", metric: "Approval cycle time <4 hrs" },
  { id: "F-10", name: "Influencer payment pipeline (Razorpay)", module: "COLLABORATE", priority: "P1", status: "Designed", metric: "Milestone payment release <1 min" }
]

const USABILITY_ROUNDS = [
  {
    round: "Round 1",
    modules: "CREATE + DEPLOY Module Prototypes",
    participants: "8 (3 Content managers, 2 SEO leads, 2 Growth Heads, 1 Founder)",
    sus: "67",
    findings: [
      { type: "critical", label: "Deploy button anxiety", text: "4 of 8 users hesitated before hitting 'Push Live' due to fear of breaking the site.", fix: "Added a pre-deploy review modal detailing changed files and staging page URL previews." },
      { type: "high", label: "Keyword results clutter", text: "Users were overwhelmed by the density of keyword research tables.", fix: "Default view simplified to search volume, difficulty, and gap. Other data moved to details tab." },
      { type: "medium", label: "Hidden social wizard", text: "Content managers did not notice they could auto-generate social posts from live blogs.", fix: "Added a persistent 'Create Social Posts' CTA banner immediately upon publish success." }
    ]
  },
  {
    round: "Round 2",
    modules: "CREATE + DEPLOY + TRACK Integration",
    participants: "11 (4 Content editors, 3 Marketing directors, 2 SEOs, 2 Founders)",
    sus: "79",
    findings: [
      { type: "high", label: "Attribution sort default", text: "Attribution tables default sorted by publication date; users immediately wanted to sort by revenue.", fix: "Updated default sorting index to Attributed Revenue (descending) across dashboard lists." },
      { type: "high", label: "Founder information density", text: "Founders were dropped into detailed lead tables and struggled to locate aggregated numbers.", fix: "Implemented role-based dashboard landing pages: Founders see Executive metrics, managers see tools." }
    ]
  }
]

// ─── Sub-components ───────────────────────────────────────────────────────────

function FlowViewer({ flows }) {
  const [active, setActive] = useState(0)
  const flow = flows[active]

  return (
    <div className="mu-flow-viewer">
      <div className="mu-flow-tabs">
        {flows.map((f, i) => (
          <button
            key={f.flow_id}
            className={`mu-flow-tab${i === active ? ' active' : ''}`}
            onClick={() => setActive(i)}
          >
            <span className="mu-flow-tab-id">{f.flow_id}</span>
            <span className="mu-flow-tab-name">{f.flow_name}</span>
          </button>
        ))}
      </div>

      <div className="mu-flow-meta-bar">
        <div className="mu-fmeta">
          <span className="mu-fmeta-k">Actor</span>
          <span className="mu-fmeta-v">{flow.actor}</span>
        </div>
        <div className="mu-fmeta">
          <span className="mu-fmeta-k">Trigger</span>
          <span className="mu-fmeta-v">{flow.trigger}</span>
        </div>
        <div className="mu-fmeta mu-fmeta--goal">
          <span className="mu-fmeta-k">Goal</span>
          <span className="mu-fmeta-v">{flow.goal}</span>
        </div>
      </div>

      <div className="mu-flow-steps">
        {flow.steps.map((s, i) => (
          <div className="mu-flow-step" key={s.step}>
            <div className="mu-step-spine">
              <div className="mu-step-circle">{s.step}</div>
              {i < flow.steps.length - 1 && <div className="mu-step-line" />}
            </div>
            <div className="mu-step-body">
              <div className="mu-step-screen">{s.screen}</div>
              <p className="mu-step-action">{s.action}</p>
              {s.decision && (
                <div className="mu-step-decision" style={{ marginTop: '0.75rem', borderLeft: '2px solid var(--mu-orange)', paddingLeft: '0.75rem', fontSize: '0.9rem', color: 'var(--mu-muted)' }}>
                  <span style={{ color: 'var(--mu-orange)', fontWeight: 600, marginRight: '0.5rem' }}>Design Decision:</span>
                  {s.decision}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      <div className="mu-flow-footer-section">
        <div>
          <span className="mu-flow-sub-label">Edge Cases Handled</span>
          <div className="mu-edge-list">
            {flow.edge_cases.map((e, i) => (
              <div className="mu-edge-case" key={i}>
                <span className="mu-edge-icon">⚠</span>
                <span>{e}</span>
              </div>
            ))}
          </div>
        </div>

        <div>
          <span className="mu-flow-sub-label">UX Metrics Tracked</span>
          <div className="mu-metrics-tags">
            {flow.metrics.map(m => (
              <span key={m} className="mu-metric-tag">{m}</span>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

// ─── Main Component ───────────────────────────────────────────────────────────

export default function MarketUCaseStudy() {
  const navigate = useNavigate()
  const pageRef = useRef(null)

  const [activePersona, setActivePersona] = useState(0)
  const [activeModule, setActiveModule] = useState("M-01")

  const p = PERSONAS[activePersona]

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  useEffect(() => {
    const ctx = gsap.context(() => {
      // Reveal single items
      gsap.utils.toArray('.mu-reveal').forEach(el => {
        gsap.fromTo(el,
          { y: 30, opacity: 0 },
          {
            y: 0, opacity: 1, duration: 0.8, ease: 'power3.out',
            scrollTrigger: { trigger: el, start: 'top 85%' }
          }
        )
      })

      // Reveal list items
      gsap.utils.toArray('.mu-reveal-stagger').forEach(parent => {
        gsap.fromTo(Array.from(parent.children),
          { y: 24, opacity: 0 },
          {
            y: 0, opacity: 1, duration: 0.7, ease: 'power3.out', stagger: 0.08,
            scrollTrigger: { trigger: parent, start: 'top 85%' }
          }
        )
      })

      // Counter animation for metrics
      OUTCOMES.forEach(({ id, to, suffix }) => {
        const el = document.querySelector('#' + id)
        if (!el) return
        const proxy = { val: 0 }
        gsap.to(proxy, {
          val: to, duration: 2, ease: 'power2.out',
          scrollTrigger: { trigger: el, start: 'top 85%' },
          onUpdate() { el.textContent = Math.round(proxy.val) + suffix }
        })
      })
    }, pageRef)

    return () => ctx.revert()
  }, [])

  return (
    <motion.div
      ref={pageRef}
      className="mu-page"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <button className="mu-back-btn" onClick={() => navigate('/')}>
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path d="M10 3L5 8L10 13" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
        </svg>
        Back to Work
      </button>

      {/* ══ COVER ═══════════════════════════════════════════════════════════ */}
      <header className="mu-cover">
        <div className="mu-cover-bg" aria-hidden="true" />
        
        {/* Floating thematic elements */}
        <div className="mu-cover-bubbles" aria-hidden="true">
          <div className="mu-bubble mu-bubble--1">
            <span className="mu-bubble-icon">KW</span>
            <span>Keyword: CPA exam fees India</span>
          </div>
          <div className="mu-bubble mu-bubble--2">
            <span className="mu-bubble-icon">DEPLOY</span>
            <span>Committed to /content branch</span>
          </div>
          <div className="mu-bubble mu-bubble--3">
            <span className="mu-bubble-icon">TRACK</span>
            <span>Lead #4829 Attributed to Blog</span>
          </div>
          <div className="mu-bubble mu-bubble--4">
            <span className="mu-bubble-icon">Payout</span>
            <span>Razorpay milestone triggered</span>
          </div>
        </div>

        <div className="mu-cover-inner mu-container">
          <div className="mu-cover-meta">
            <span className="mu-eyebrow">Case Study</span>
            <span className="mu-cover-dot" />
            <span className="mu-attr-val" style={{ fontSize: '0.8rem', color: 'var(--mu-orange)' }}>B2B SaaS</span>
          </div>

          <h1 className="mu-cover-title mu-gradient-orange">
            MarketU
          </h1>

          <p className="mu-cover-subtitle">
            How we built the world's first autonomous marketing operating system — a platform that creates content, deploys it to Vercel/DigitalOcean, tracks leads in XOLOX, and manages influencer agreements.
          </p>

          <div className="mu-cover-attrs">
            <div className="mu-cover-attr">
              <span className="mu-attr-label">My Roles</span>
              <span className="mu-attr-val">Sole PM & UX Designer</span>
            </div>
            <div className="mu-cover-attr">
              <span className="mu-attr-label">Build Site</span>
              <span className="mu-attr-val">NorthStar Academy</span>
            </div>
            <div className="mu-cover-attr">
              <span className="mu-attr-label">Timeline</span>
              <span className="mu-attr-val">{META.timeline}</span>
            </div>
            <div className="mu-cover-attr">
              <span className="mu-attr-label">Status</span>
              <span className="mu-attr-val" style={{ color: '#4ade80' }}>Production Live</span>
            </div>
          </div>

          <div className="mu-scroll-hint" onClick={() => document.getElementById('mu-exec-summary')?.scrollIntoView({ behavior: 'smooth' })}>
            <div className="mu-scroll-mouse">
              <div className="mu-scroll-wheel" />
            </div>
            <span>Explore Case Study</span>
          </div>
        </div>
      </header>

      <div className="mu-container mu-content">
        {/* ══ CH01 — EXECUTIVE SUMMARY ════════════════════════════════════ */}
        <section className="mu-section" id="mu-exec-summary">
          <div className="mu-glow mu-glow--orange" />
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">01</span>
            <span className="mu-eyebrow">Executive Summary</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            One platform. <span className="mu-orange">Zero manual coordination.</span> Full attribution.
          </h2>

          <div className="mu-exec-grid mu-reveal-stagger">
            <div className="mu-exec-card">
              <span className="mu-exec-tag mu-exec-tag--problem">The Friction</span>
              <p className="mu-exec-body">Marketing heads at Indian EdTechs managed 7+ disconnected systems (Semrush, Notion, Google Docs, WordPress, Buffer, Zoom, WhatsApp). No one knew which content pieces actually generated WhatsApp leads or admissions.</p>
            </div>
            <div className="mu-exec-card">
              <span className="mu-exec-tag mu-exec-tag--solution">The Loop</span>
              <p className="mu-exec-body">GrowOS automates the complete cycle. It researches keyword difficulty, writes drafts, pushes files live via Git, tracks leads to specific UTM content IDs, and coordinates contractor payout milestones.</p>
            </div>
          </div>

          <div className="mu-challenge-box mu-reveal">
            <span className="mu-challenge-label">The Category Differentiator</span>
            <p className="mu-challenge-text">
              Semrush tells your team what is broken. GrowOS logs onto your repository and fixes it.
            </p>
          </div>

          <div className="mu-outcomes-grid mu-reveal-stagger">
            {OUTCOMES.map(o => (
              <div className="mu-outcome-card" key={o.id}>
                <span id={o.id} className="mu-outcome-num">{o.to}{o.suffix}</span>
                <span className="mu-outcome-label">{o.label}</span>
                <span className="mu-outcome-sub">Verified in NorthStar Academy production logs</span>
              </div>
            ))}
          </div>
        </section>

        {/* ══ CH02 — DISCOVERY ════════════════════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">02</span>
            <span className="mu-eyebrow">Discovery & Research</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Auditing workflows. <span className="mu-orange">Interviews across 31 teams.</span> Uncovering the execution gap.
          </h2>

          <p className="mu-body mu-reveal">
            To design an autonomous platform, I embedded myself within the NorthStar growth squad for 4 weeks. I audited Chrome tabs, calculated revision message overheads, and cataloged tool-switching behaviors.
          </p>

          <div className="mu-research-intro mu-reveal">
            <div className="mu-research-findings-grid">
              <div className="mu-finding-box">
                <span className="mu-finding-val">11.4 tabs</span>
                <span className="mu-finding-desc">Open concurrently by content creators</span>
              </div>
              <div className="mu-finding-box">
                <span className="mu-finding-val">47 texts</span>
                <span className="mu-finding-desc">WhatsApp messages exchanged to approve 1 post</span>
              </div>
              <div className="mu-finding-box">
                <span className="mu-finding-val">18 days</span>
                <span className="mu-finding-desc">Median time to go from draft to live WordPress page</span>
              </div>
              <div className="mu-finding-box">
                <span className="mu-finding-val">92% opaque</span>
                <span className="mu-finding-desc">Leads originating with zero attribution source data</span>
              </div>
            </div>
          </div>

          <div className="mu-research-content-panel mu-reveal">
            <h3 className="mu-sub-heading">Methodology Deep Dive</h3>
            <div className="mu-research-meta-grid">
              <div>
                <div className="mu-rmeta-label">Selected Method</div>
                <div className="mu-rmeta-val">{RESEARCH_METHODS[0].method}</div>
              </div>
              <div>
                <div className="mu-rmeta-label">Format & Scope</div>
                <div className="mu-rmeta-val" style={{ fontSize: '1rem', fontWeight: 500 }}>{RESEARCH_METHODS[0].duration}</div>
                <div className="mu-rmeta-detail">{RESEARCH_METHODS[0].metric} {RESEARCH_METHODS[0].metricLabel} audited</div>
              </div>
            </div>

            <div className="mu-research-split">
              <div>
                <span className="mu-research-col-title">What We Audited</span>
                <p className="mu-body" style={{ fontSize: '0.95rem' }}>
                  shadowed team logs and monitored mouse pathways while executing technical keyword pushes, visual copy edits, and developer sync backlogs.
                </p>
              </div>
              <div>
                <span className="mu-research-col-title">Key Audit Insights</span>
                <ul className="mu-research-bullets">
                  {RESEARCH_METHODS[0].bullets.map((b, i) => (
                    <li key={i}>{b}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* ══ CH03 — SYNTHESIS & INSIGHTS ══════════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-glow mu-glow--peach" />
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">03</span>
            <span className="mu-eyebrow">Synthesis & Themes</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Affinity mappings. <span className="mu-orange">Systemic failures.</span> Tool bloat.
          </h2>

          <div className="mu-themes-grid mu-reveal-stagger" style={{ marginBottom: '4rem' }}>
            {AFFINITY_THEMES.map((t, i) => (
              <div className="mu-theme-card" key={i}>
                <div className="mu-theme-header">
                  <h3 className="mu-theme-title">{t.theme}</h3>
                  <span className="mu-theme-count">Affinity Group</span>
                </div>
                <p className="mu-theme-desc">{t.desc}</p>
                <div className="mu-theme-stat">{t.stat}</div>
              </div>
            ))}
          </div>

          <h3 className="mu-sub-heading mu-reveal">Jobs to be Done (JTBD)</h3>
          <div className="mu-jtbd-list mu-reveal-stagger">
            {JTBDS.map((j) => (
              <div className="mu-jtbd-item" key={j.id}>
                <span className="mu-jtbd-id">{j.id}</span>
                <div className="mu-jtbd-body">
                  <div className="mu-jtbd-job">{j.job}</div>
                  <div className="mu-jtbd-meta-line">
                    <div className="mu-jtbd-meta-cell">Actor: <span>{j.actor}</span></div>
                    <div className="mu-jtbd-meta-cell">Current workaround: <span>{j.workaround}</span></div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ══ CH04 — KEY INSIGHTS ══════════════════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">04</span>
            <span className="mu-eyebrow">Key Insights</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Synthesizing core rules <span className="mu-orange">for platform strategy.</span>
          </h2>

          <div className="mu-insights-grid mu-reveal-stagger">
            {KEY_INSIGHTS.map((ins, i) => (
              <div className="mu-insight-card" key={i}>
                <span className="mu-insight-num">{ins.num}</span>
                <h3 className="mu-insight-title">{ins.title}</h3>
                <p className="mu-insight-evidence">{ins.evidence}</p>
                <div className="mu-insight-principle">
                  <span className="mu-principle-tag">Design Principle</span>
                  <p className="mu-principle-body">{ins.desc || ins.principle}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ══ CH05 — PERSONAS ══════════════════════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">05</span>
            <span className="mu-eyebrow">User Personas</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Different roles. <span className="mu-orange">Aligned on outcomes.</span> Separated by execution layers.
          </h2>

          <div className="mu-persona-switcher mu-reveal">
            <div className="mu-persona-tabs">
              {PERSONAS.map((pers, idx) => (
                <button
                  key={pers.id}
                  className={`mu-persona-tab${idx === activePersona ? ' active' : ''}`}
                  onClick={() => setActivePersona(idx)}
                >
                  {pers.name}
                </button>
              ))}
            </div>

            <div className="mu-persona-card">
              <div className="mu-pcard-header">
                <div className="mu-pcard-avatar">{p.avatar}</div>
                <div className="mu-pcard-title-block">
                  <h3 className="mu-pcard-name">{p.name}</h3>
                  <span className="mu-pcard-archetype">{p.archetype}</span>
                </div>
              </div>

              <blockquote className="mu-pcard-quote">"{p.quote}"</blockquote>

              <div className="mu-pcard-grid">
                <div className="mu-pcard-section">
                  <span className="mu-ps-title">Profile</span>
                  <div className="mu-pcard-meta-list">
                    <div className="mu-pmeta-item">
                      <span className="mu-pmeta-k">Age</span>
                      <span className="mu-pmeta-v">{p.age}</span>
                    </div>
                    <div className="mu-pmeta-item">
                      <span className="mu-pmeta-k">Role</span>
                      <span className="mu-pmeta-v">{p.role}</span>
                    </div>
                    <div className="mu-pmeta-item">
                      <span className="mu-pmeta-k">Location</span>
                      <span className="mu-pmeta-v">{p.location}</span>
                    </div>
                    <div className="mu-pmeta-item">
                      <span className="mu-pmeta-k">Company</span>
                      <span className="mu-pmeta-v">{p.company}</span>
                    </div>
                  </div>
                  
                  <span className="mu-ps-title" style={{ marginTop: '1.5rem' }}>Current Stack</span>
                  <div className="mu-pcard-tools-list">
                    {p.tools.map(t => (
                      <span className="mu-ptool-pill" key={t}>{t}</span>
                    ))}
                  </div>
                </div>

                <div className="mu-pcard-section">
                  <span className="mu-ps-title">Goals</span>
                  <ul className="mu-pcard-bullets">
                    {p.goals.map((g, i) => <li key={i}>{g}</li>)}
                  </ul>

                  <span className="mu-ps-title" style={{ marginTop: '1.5rem' }}>Frustrations</span>
                  <ul className="mu-pcard-bullets mu-pcard-bullets--frustrations">
                    {p.frustrations.map((f, i) => <li key={i}>{f}</li>)}
                  </ul>
                </div>

                <div className="mu-pcard-success-box">
                  <span className="mu-success-badge">Ideal Success Flow:</span>
                  {p.success}
                </div>
              </div>

              <span className="mu-pcard-state">{p.state}</span>
            </div>
          </div>
        </section>

        {/* ══ CH06 — DESIGN SCHEMAS ════════════════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">06</span>
            <span className="mu-eyebrow">Design Principles & Strategy</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Translating JTBDs <span className="mu-orange">into core design priorities.</span>
          </h2>

          <div className="mu-hmw-grid mu-reveal-stagger">
            {HMW_QUESTIONS.map((h, i) => (
              <div className="mu-hmw-card" key={i}>
                <span className="mu-hmw-title">How Might We...</span>
                <p className="mu-hmw-question">"{h.hmw}"</p>
                <span className="mu-hmw-target">{h.target}</span>
              </div>
            ))}
          </div>

          <h3 className="mu-sub-heading mu-reveal">Product Design Principles</h3>
          <div className="mu-principles-grid mu-reveal-stagger">
            {DESIGN_PRINCIPLES.map((pr, i) => (
              <div className="mu-principle-card" key={i}>
                <h4 className="mu-principle-header">
                  <span className="mu-principle-dot" />
                  {pr.title}
                </h4>
                <p className="mu-principle-desc">{pr.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ══ CH07 — INFORMATION ARCHITECTURE ══════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">07</span>
            <span className="mu-eyebrow">Information Architecture</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Mapping the loop. <span className="mu-orange">The 5-Module Marketing Engine.</span>
          </h2>

          <div className="mu-ia-intro mu-reveal">
            <div className="mu-ia-concept-box">
              <span className="mu-eyebrow" style={{ color: 'var(--mu-orange)' }}>Navigational Concept</span>
              <p className="mu-body" style={{ margin: '0.5rem 0 0', fontSize: '1.05rem', color: '#fff' }}>
                Instead of a traditional sidebar navigation, the GrowOS layout centers around the cyclical marketing loop: CREATE → DEPLOY → DISTRIBUTE → TRACK → COLLABORATE.
              </p>
            </div>
          </div>

          <div className="mu-modules-accordion mu-reveal">
            {IA_MODULES.map((m) => {
              const isActive = activeModule === m.id
              return (
                <div className={`mu-module-item${isActive ? ' active' : ''}`} key={m.id}>
                  <button className="mu-module-trigger" onClick={() => setActiveModule(isActive ? "" : m.id)}>
                    <div className="mu-mtrigger-left">
                      <span className="mu-mtrigger-icon">{m.id === "M-01" ? "✎" : m.id === "M-02" ? "☁" : m.id === "M-03" ? "☍" : m.id === "M-04" ? "📈" : "👥"}</span>
                      <div>
                        <span className="mu-mtrigger-name">{m.name}</span>
                        <span className="mu-mtrigger-tagline"> — {m.tagline}</span>
                      </div>
                    </div>
                    <span className={`mu-module-badge mu-module-badge--${m.status}`}>
                      {m.status === 'live' ? 'Live' : m.status === 'partial' ? 'Beta' : 'Roadmap'}
                    </span>
                  </button>

                  {isActive && (
                    <div className="mu-module-panel">
                      <div className="mu-mpanel-grid">
                        {m.tools.map((t, idx) => (
                          <div className="mu-subtool-card" key={idx}>
                            <h4 className="mu-subtool-header">{t.name}</h4>
                            <p className="mu-subtool-desc">{t.desc}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </section>

        {/* ══ CH08 — UX FLOWS ══════════════════════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">08</span>
            <span className="mu-eyebrow">Interactive UX Flows</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Testing paths. <span className="mu-orange">Interactive flow simulator.</span>
          </h2>

          <p className="mu-body mu-reveal">
            Toggle through three core product paths below to inspect the step actions, design decisions, edge cases, and metrics tracked during research:
          </p>

          <div className="mu-reveal">
            <FlowViewer flows={UX_FLOWS} />
          </div>
        </section>

        {/* ══ CH09 — INTEGRATIONS & ARCHITECTURE ═══════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">09</span>
            <span className="mu-eyebrow">Technical Architecture</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Connecting code to search. <span className="mu-orange">Integrations matrix.</span>
          </h2>

          <div className="mu-table-container mu-reveal">
            <table className="mu-table">
              <thead>
                <tr>
                  <th>API Integration</th>
                  <th>Purpose</th>
                  <th>Auth Model</th>
                  <th>Criticality</th>
                </tr>
              </thead>
              <tbody>
                {INTEGRATIONS.map((int, i) => (
                  <tr key={i}>
                    <td style={{ fontWeight: 600, color: '#fff' }}>{int.name}</td>
                    <td>{int.purpose}</td>
                    <td style={{ color: 'var(--mu-muted)' }}>{int.auth}</td>
                    <td>
                      <span className={`mu-criticality-badge mu-criticality-badge--${int.criticality.toLowerCase()}`}>
                        {int.criticality}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <h3 className="mu-sub-heading mu-reveal">Feature Release Roadmap & Priorities</h3>
          <div className="mu-table-container mu-reveal">
            <table className="mu-table">
              <thead>
                <tr>
                  <th>Feature ID</th>
                  <th>Scope Name</th>
                  <th>Module</th>
                  <th>Priority</th>
                  <th>Build Status</th>
                  <th>Release Target Metric</th>
                </tr>
              </thead>
              <tbody>
                {PRIORITIZATION.map((pr, i) => (
                  <tr key={i}>
                    <td style={{ color: 'var(--mu-orange)', fontWeight: 600 }}>{pr.id}</td>
                    <td style={{ color: '#fff', fontWeight: 500 }}>{pr.name}</td>
                    <td>{pr.module}</td>
                    <td><span style={{ fontWeight: 600 }}>{pr.priority}</span></td>
                    <td>
                      <span style={{
                        color: pr.status === 'Built' ? '#4ade80' : pr.status === 'In build' ? '#facc15' : 'var(--mu-muted)',
                        fontSize: '0.85rem'
                      }}>{pr.status}</span>
                    </td>
                    <td style={{ fontSize: '0.88rem', color: 'var(--mu-muted)' }}>{pr.metric}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* ══ CH10 — USABILITY TESTING ═════════════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">10</span>
            <span className="mu-eyebrow">Usability Testing</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Testing prototypes. <span className="mu-orange">Iterating based on user anxiety.</span>
          </h2>

          <div className="mu-testing-timeline mu-reveal-stagger">
            {USABILITY_ROUNDS.map((r, i) => (
              <div className="mu-round-box" key={i}>
                <div className="mu-round-header">
                  <div>
                    <h3 className="mu-round-title">{r.round} — {r.modules}</h3>
                    <p className="mu-body" style={{ margin: '0.5rem 0 0', fontSize: '0.9rem', color: 'var(--mu-muted)' }}>
                      Cohort size: {r.participants}
                    </p>
                  </div>
                  <div className="mu-round-sus">
                    <span className="mu-sus-val">{r.sus}</span>
                    <span className="mu-sus-label">Average SUS Score</span>
                  </div>
                </div>

                <div className="mu-findings-list">
                  {r.findings.map((f, idx) => (
                    <div className={`mu-finding-item mu-finding-item--${f.type}`} key={idx}>
                      <div className="mu-f-label">
                        <span className={`mu-f-severity mu-f-severity--${f.type}`}>{f.type}</span>
                        {f.label}
                      </div>
                      <p className="mu-f-text">"{f.text}"</p>
                      <p className="mu-f-fix"><span>Fix Applied:</span> {f.fix}</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="mu-testing-quotes mu-reveal">
            <h3 className="mu-sub-heading">Tester Feedback</h3>
            <div className="mu-quotes-grid">
              <div className="mu-quote-card">
                <p className="mu-qcard-body">
                  "This is the first time I've ever seen a tool that actually shows me which blog is making me money. This changes how I brief my content team."
                </p>
                <span className="mu-qcard-author">— Marketing Lead, EdTech Firm</span>
              </div>
              <div className="mu-quote-card">
                <p className="mu-qcard-body">
                  "The deploy button scared me for a second, but then I saw the changes preview and it made perfect sense. I click deploy now without hesitation."
                </p>
                <span className="mu-qcard-author">— Content Manager</span>
              </div>
            </div>
          </div>
        </section>

        {/* ══ CH11 — RETROSPECTIVE ══════════════════════════════════════════ */}
        <section className="mu-section">
          <div className="mu-section-label mu-reveal">
            <span className="mu-ch-num">11</span>
            <span className="mu-eyebrow">Retrospective & Roadmap</span>
          </div>

          <h2 className="mu-section-title mu-reveal">
            Roadmap targets <span className="mu-orange">and key lessons from Month 1.</span>
          </h2>

          <div className="mu-retro-grid mu-reveal-stagger" style={{ marginBottom: '4rem' }}>
            <div className="mu-retro-card">
              <h3 className="mu-retro-card-title">
                <span className="mu-retro-icon">✓</span>
                What Worked
              </h3>
              <ul className="mu-retro-items">
                <li>
                  <span className="mu-retro-item-title">Staging previews build trust</span>
                  Direct deployments caused anxiety. Pre-deploy staging modals converted managers from hesitant to confident.
                </li>
                <li>
                  <span className="mu-retro-item-title">Dogfooding is best research</span>
                  Building GrowOS while using it inside NorthStar Academy allowed immediate discovery of outline editor quirks.
                </li>
              </ul>
            </div>

            <div className="mu-retro-card mu-retro-card--questions">
              <h3 className="mu-retro-card-title">
                <span className="mu-retro-icon">?</span>
                Open Strategy Questions
              </h3>
              <ul className="mu-retro-items">
                <li>
                  <span className="mu-retro-item-title">Webflow & CMS-native support?</span>
                  How do we serve customers with hosted sites not managed in GitHub? Will we need REST integration structures?
                </li>
                <li>
                  <span className="mu-retro-item-title">Compliance checks for regulated sectors</span>
                  When AI generates details on taxation, we need strict editor check gates to satisfy legal compliance.
                </li>
              </ul>
            </div>
          </div>

          <h3 className="mu-sub-heading mu-reveal">GTM & Commercial Tiers</h3>
          <div className="mu-table-container mu-reveal">
            <table className="mu-table">
              <thead>
                <tr>
                  <th>Pricing Tier</th>
                  <th>Monthly Rate</th>
                  <th>Modules Included</th>
                  <th>Ideal Segment Target</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td style={{ fontWeight: 700 }}>Starter</td>
                  <td style={{ color: 'var(--mu-orange)', fontWeight: 600 }}>₹4,999</td>
                  <td>CREATE + DEPLOY (Modules 1 + 2)</td>
                  <td>1–2 person content teams</td>
                </tr>
                <tr>
                  <td style={{ fontWeight: 700 }}>Growth</td>
                  <td style={{ color: 'var(--mu-orange)', fontWeight: 600 }}>₹9,999</td>
                  <td>CREATE + DEPLOY + DISTRIBUTE (Modules 1–3)</td>
                  <td>5–10 person marketing squads</td>
                </tr>
                <tr>
                  <td style={{ fontWeight: 700 }}>Agency / Enterprise</td>
                  <td style={{ color: 'var(--mu-orange)', fontWeight: 600 }}>₹24,999</td>
                  <td>All 5 Modules + XOLOX + Razorpay</td>
                  <td>Large EdTech institutes, multi-program centers</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* ══ FOOTER NAV ═══════════════════════════════════════════════════ */}
        <div className="mu-footer-nav mu-reveal">
          <button className="mu-nav-btn mu-nav-btn--prev" onClick={() => navigate('/work/xolox')}>
            <span className="mu-nav-arrow">←</span>
            <div className="mu-nav-btn-content">
              <span className="mu-nav-btn-label">Previous</span>
              <span className="mu-nav-btn-name">Xolox CRM</span>
            </div>
          </button>

          <button className="mu-nav-btn mu-nav-btn--next" onClick={() => navigate('/work/greeto')}>
            <div className="mu-nav-btn-content">
              <span className="mu-nav-btn-label">Next Case Study</span>
              <span className="mu-nav-btn-name">Greeto.io</span>
            </div>
            <span className="mu-nav-arrow">→</span>
          </button>
        </div>
      </div>
    </motion.div>
  )
}
